---
name: CI-CD Pipeline
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: temurin
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Update dependency graph
        uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.3.3
        with:
          name: Boardgame
          path: target/*.jar
      - name: Trivy FS Scan
        run: trivy fs --format table -o trivy-report.html .
      - name: Official SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v2.0.2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOSTURL: ${{ secrets.SONAR_HOSTURL }}
      - name: SonarQube Quality Gate Check
        uses: SonarSource/sonarqube-quality-gate-action@v1.1.0
        timeout-minutes: 5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOSTURL: ${{ secrets.SONAR_HOSTURL }}
      - name: Docker Setup QEMU
        uses: docker/setup-qemu-action@v3.0.0
      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v3.3.0
      - name: Build Docker Image
        run: |
          docker build -t kolapkarvish/bg:latest
      - name: Trivy FS Scan
        run: trivy image --format table -o trivy-dockerimage-report.html
          kolapkarvish/bg:latest
      - name: Docker Login
        uses: docker/login-action@v3.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PWD }}
      - name: Push Docker Image
        run: |+
          docker push kolapkarvish/bg:latest  

            


            
